accessible_charts: true
accessible_tabs: true
analytics:
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
country:
  name: Vanuatu
  adjective: Vanuatuan
create_config_forms:
  layout: config-builder
create_goals:
  layout: goal-by-target
  previous_next_links: true
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: ../editor-instructions/
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
  - path: 'mailto:my-email-address@example.com'
    translation_key: menu.contact_us
  - path: 'https://twitter.com/MyTwitterAccount'
    translation_key: general.twitter
  - path: 'https://facebook.com/MyFacebookAccount'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Lorem ipsum
    content: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
      cursus est sed dapibus.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
  - title: Nam vestibulum
    content: |
      Nam vestibulum, purus quis porttitor imperdiet, nisl sem mollis nisl, a
      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
frontpage_goals_grid:
  title: Our data for National Sustainable Development Plan indicators
  description: >-
    Click on each goal for our National Sustainable Development Plan indicator
    data.
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: 'Vanuatu 2030: The People''s Plan'
  description: >-
    The national sustainable development goals and policy objectives outlined in
    *Vanuatu 2030: The People's Plan (National Sustainable Development Plan 2016
    to 2030)* are the overarching guide for government planning over the next 15
    years. Together they articulate a path for Vanuatu to emerge as a much
    stronger nation, renewing our traditions and values, and creating economic
    opportunities for all.
goal_image_base: /vanuatu-nsdp/assets/img/goals
goal_image_extension: jpg
goals_page:
  title: ''
  description: ''
graph_color_set: default
graph_color_list: []
graph_color_number: 0
header:
  include: header-default.html
header_language_toggle: dropdown
hide_empty_metadata: true
indicator_config_form:
  dropdowns: []
languages:
  - en
languages_public: []
map_layers: []
map_options:
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /goals
    translation_key: general.goals
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq
  - path: /news
    translation_key: menu.updates
metadata_edit_url: ../editor-instructions/
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
news:
  category_links: false
non_global_metadata: indicator.national_metadata
remote_data_prefix: _build
reporting_status:
  title: ''
  description: ''
  disaggregation_tabs: false
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
sharethis_property: ''
site_config_form:
  dropdowns: []
validate_indicator_config: false
validate_site_config: false
